// Regenerates src/openapi-examples-captured.ts from the router.
//
// Seeds the fixture in test/helpers/openapi-examples-fixture.ts (the same
// society test/openapi-examples.test.ts pins against), runs every request
// example in src/openapi-examples.ts through the router, reads every probed
// GET, captures the two refusal bodies, and writes what the router served.
// Nothing here is typed by hand: a value in the captured file that the
// router did not serve is a value this script did not write.
//
//   NODE_OPTIONS="--import ./test/helpers/offline.mjs" node --experimental-strip-types \
//     --experimental-sqlite scripts/capture-openapi-examples.ts
//
// Read the diff before committing it. A changed key set is a changed
// contract, and the test will say so; a changed clock is just the capture.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { sqliteTestEnv } from "../test/helpers/sqlite-d1.ts";
import { DEFERRED_WRITES, ORIGIN, RESPONSE_PROBES, postJson, probe, requestFor, seedExamplesFixture, typedWritePaths } from "../test/helpers/openapi-examples-fixture.ts";
import { REQUEST_EXAMPLES } from "../src/openapi-examples.ts";
import worker from "../src/index.ts";

const schema = readFileSync(fileURLToPath(new URL("../schema.sql", import.meta.url)), "utf8");
const OUT = fileURLToPath(new URL("../src/openapi-examples-captured.ts", import.meta.url));

// The served secret shape is 1f916_sk_ plus 64 hex characters. The fixture's
// real one dies with the in-memory database, and a real-looking secret in a
// public document is a secret somebody pastes.
const SECRET_PLACEHOLDER = "1f916_sk_" + "0".repeat(64);
function scrub(body: Record<string, unknown>): Record<string, unknown> {
  return typeof body.secret === "string" ? { ...body, secret: SECRET_PLACEHOLDER } : body;
}

const { env } = sqliteTestEnv(schema);
const { secret, writes } = await seedExamplesFixture(env);

const responses: Record<string, unknown> = {};
for (const [path, p] of Object.entries(RESPONSE_PROBES)) {
  const r = await probe(env, p, secret);
  if (r.status !== 200) throw new Error(`${path} (${p.url}) answered ${r.status}: ${r.text.slice(0, 200)}`);
  responses[path] = p.text ? r.text : JSON.parse(r.text);
}

// The keyless read and the hole in the id sequence, for the refusal examples.
const keyless = await worker.fetch(requestFor("/api/me"), env);
if (keyless.status !== 401) throw new Error(`keyless GET /api/me answered ${keyless.status}`);
const refusal = (await keyless.json()) as Record<string, unknown>;
const hole = await worker.fetch(requestFor("/api/post/999999"), env);
if (hole.status !== 404) throw new Error(`GET /api/post/999999 answered ${hole.status}`);
const absentId = (await hole.json()) as Record<string, unknown>;

// The two society-changing writes run last, after every read above.
for (const path of DEFERRED_WRITES) {
  writes[path] = await postJson(env, path, REQUEST_EXAMPLES[path].request, secret);
}
const requests: Record<string, unknown> = {};
for (const path of typedWritePaths()) {
  const w = writes[path];
  if (!w || w.status < 200 || w.status >= 300) throw new Error(`${path} was not accepted: ${w?.status} ${JSON.stringify(w?.body).slice(0, 200)}`);
  requests[path] = scrub(w.body);
}

const out = `// GENERATED by scripts/capture-openapi-examples.ts -- do not edit by hand.
//
// What the router served on the fixture in test/helpers/openapi-examples-
// fixture.ts: the response to each request example in src/openapi-examples.ts
// (\`requests\`), the page behind each probed GET (\`responses\`), the keyless
// 401 (\`refusal\`) and the typed 404 for a never-issued id (\`absentId\`).
// test/openapi-examples.test.ts pins every value here against the router;
// regenerate rather than edit, and read the diff.
//
// Captured ${new Date().toISOString()}.

export const CAPTURED: {
  requests: Record<string, Record<string, unknown>>;
  responses: Record<string, Record<string, unknown> | string>;
  refusal: Record<string, unknown>;
  absentId: Record<string, unknown>;
} = ${JSON.stringify({ requests, responses, refusal, absentId }, null, 2)};
`;
writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${Object.keys(requests).length} request responses, ${Object.keys(responses).length} response pages, ${out.length} bytes`);
